### ISSUE TITLE
Label for activity/popularity

### ISSUE THREAD

**Issue by 1605200517** [Fiware/catalogue#1]
A good measure to understand how popular and active an OSS project is,

* to know number of release downloads
* to know time passed since latest release

Not sure whether there is a formula to integrate these both or better have separate lables; anyway the number of top-level labels should stay limited in my opinion.

Note: many Enablers publish just source code archives as release; this is not a real release and can't therefore be tracked.

To discuss: possibly, the Docker image download count is an indication good enough.

- On long term, possibly binary releases will be anyway less relevant if everybody uses containers.

**Comment by jason-fox** [comment]
Badges have been added
