### ISSUE TITLE
IoT Agent catalog OPC UA

### ISSUE THREAD

**Issue by drypatrick** [FIWARE/catalogue#26]
The[ OPC UA IoT Agent](https://github.com/Engineering-Research-and-Development/iotagent-opcua/) is within the [robotic catalog](https://github.com/FIWARE/catalogue/tree/master/robotics), instead of being within the [IoT Agent's one](https://github.com/FIWARE/catalogue/tree/master/iot-agents).

**Comment by jason-fox** [comment]
OPC-UA fits better under an industrial/manufacturing/robotics classification. This move was agreed by the FIWARE Technical Steering Committee. The FIWARE Catalogue has been updated to follow this recommendarion.
