### ISSUE TITLE
Add static quality label

### ISSUE THREAD

**Issue by synergiator** [FIWARE/catalogue#3]
Sonarqube uses already labels for static code quality.
This data should be collected and introduced as new label.
Also, minimum source quality label should control whether a release is allowed to pass RC status.

**Comment by jason-fox** [comment]
Labels/Badging requirements for code quality within FIWARE enablers should be raised against the [Developer's Guidelines](https://github.com/Fiware/developmentGuidelines/blob/master/development.mediawiki#code-quality) - if you wish to strengthen the statements, please raise it there.

I think the actual requirement will depend on the language used. For example, I would like to enforce a linting step (e.g. prettier, Checkstyle) as a pre-testing step on builds which should cover the _minimum source quality_ part of your statement.

I assume there would be different minimum thresholds for *Incubated*  vs *Mature* Generic Enablers.

**Comment by jason-fox** [comment]
A decision has been made not to add this to the catalogue umbrella repo for now. Closing
