### ISSUE TITLE
few comments on release page

### ISSUE THREAD

**Issue by chicco785** [Fiware/catalogue#4]
1. "latest" is not a good way of versioning :) we need to ask a developers to do an effort and provide actual versioning.

1. for some enablers it looks like that you include also "side" projects (e.g. the project to deploy the service or to make it a container), i don't think we should list this project in release. this should be eventually linked from the "core" repository of the project.

1. to solve the "issue" of linking docker, we may add the request to use a badge to link with the official image.

**Comment by jason-fox** [comment]
1. I agree `latest` is only a placeholder until a release is specified - it shouldn't be found in the final release.
2. I believe the side projects should be released **with the same label** as well this ensures that the versioned Docker image is reproducible and that the snapshot documentation for each released version is available.
3. Adding a Docker badge is part of the new Developer's Guidelines, however the new guideline won't be enforced until 7.5 so won't apply to the current release.

**Comment by chicco785** [comment]
2. I agree they should be properly labeled. What I wanted to say, it looks confusing to me to have them in the platform release note. Especially the case of "knowage" looks quite weird to me, also the documentation is listed in the release...

**Comment by jason-fox** [comment]
Documentation is part of the release. In most cases it is held in the same repository as the code.
Where it has been separated **both** repos should release versioned together.

Getting various projects to fix versions (e.g knowage) to fix versions is one of the issues to be resolved before closing the release.

The alternative is to confirm that the "side" project is not maintained and should be removed from the catalogue.

I would have no problem with removing  the side projects from the 7.4. **final** release, but at the moment for the release **candidates**, I'll keep them in to track the outstanding issues (missing labels, wrong version included etc.)

**Comment by jason-fox** [comment]
* `latest` placeholders removed where semVer tags have been specified
* Side Projects removed from **Final** 7.4 [Release Note](https://github.com/Fiware/catalogue/releases/tag/FIWARE_7.4)
* Docker badging moved to separate issue - #9
